[package]
name = "Stickere"
version = "1.0.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.0", features = ["bundled"] }
eframe = "0.28.1"

[[bin]]
name = "Sickere"
path = "src/main.rs"